name: 🐞 Bug Report
title: '[bug] '
description: Report a bug
labels: ['type: bug', 'status: needs triage']

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/persiliao/brew-services-manage/issues?q=is%3Aissue) about this problem first.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a reproduction repo or steps to reproduce the behaviour.
      placeholder: |
        Please provide a minimal reproduction or steps to reproduce, see this guide https://stackoverflow.com/help/minimal-reproducible-example
        Why reproduction is required? see this article https://antfu.me/posts/why-reproductions-are-required

  - type: textarea
    id: info
    attributes:
      label: Full System information output
      description: 'Output of `system_profiler SPHardwareDataType`'
      render: text
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
